include:
  - board: seeeduino_xiao_ble
    # shield: totem_left
    shield: settings_reset
  # - board: seeeduino_xiao_ble
    # shield: totem_right

# there is no settingsreset (needed) for the XIAO
